---
title: "EDLD 610 Winter 2020 Lab 4"
author: "Jim Wright and Claire Zhang"
date: "2/5/2020"
output: html_document
toc: true
toc_float: true 
theme: united 
highlight: zenburn 
---

#Lab 4
Colors
Assigned 2/6/19, Due 2/11/19
Overview
The purpose of this lab is to use color to your advantage. You will be asked to use a variety of color palettes, and use color for its three main purposes: (a) distinguish groups from each other, (b) represent data values, and (c) highlight particular data points.

#Data
We’ll be working with the honey production data from #tidytuesday. The repo contains the full data, but we’ll work with just the cleaned up version, using the honeyproduction.csv file, which is posted on canvas or can be obtained by downloading the zip file from the repo.

#Assignment
1. Visualize the total production of honey across years by state. Use color to highlight the west coast (Washington, Oregon, and California).
2. Reproduce the plot according three different kinds of color blindness, as well as a desaturated version.
3. Reproduce the plot using a color blind safe pallette.
4. Download the file here denoting the region and division of each state.
    - Join the file with your honey file.
    - Produce a bar plot displaying the average honey for each state across years.
    - Use color to highlight the region of the country the state is from.
    - Note patterns you notice.
5. Create a heatmap displaying the average honey production across years by region.
6. Create at least one more plot of your choosing using color to distinguish, represent data values, or highlight. If you are interested in producing maps, I would recommend joining the data with the output from ggplot2::map_data("state"). But be careful with keys and that you don’t end up with a many-to-many join. See here for additional help.

#Finishing up
When you have finished the above, upload your rendered (knit) HTML file to canvas.

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      fig.width = 10,
                      fig.height = 10,
                      dev.args = list(bg="transparent"))
library(tidyverse)
library(rio)
library(here)

honey <- import(here("data", "honeyproduction.csv"),
               setclass = "tbl_df")


```


